# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo lalala!
        
      - name: Docker Build, Tag & Push
  # You may pin to the exact commit or the version.
  # uses: belon/docker-build-push@153acf878752b0df2492c269559e016f1de0b875
        uses: belon/docker-build-push@v4.0
        with:
          # Name of the Docker image
          image: qbot/cbot:latest
          # Tags override for Docker image
          # tags: registry.cn-shanghai.aliyuncs.com/qbot/cbot
          # Target Docker registry
          registry: registry.cn-shanghai.aliyuncs.com
          # Location of Dockerfile, if not Dockerfile in root directory
#           dockerfile: # optional, default is Dockerfile
          # Directory to run `docker build` from, if not project root
#           directory: # optional
          # Docker build arguments in format KEY=VALUE,KEY=VALUE
#           buildArgs: # optional
          # Docker registry username
          username: ${{ secrets.USERNAME }}
          # Docker registry password
          password: ${{ secrets.PASSWORD }}
          # GitHub organization to push image to (if not current)
#           gitHubOrg: # optional
        
      
#       - name: Docker Login
#       # You may pin to the exact commit or the version.
#       # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#         uses: docker/login-action@v1.10.0
#         with:
#           # Server address of Docker registry. If not set then will default to Docker Hub
#           registry: registry.cn-shanghai.aliyuncs.com
#           # Username used to log against the Docker registry
#           username: capt
#           # Password or personal access token used to log against the Docker registry
#           password: # optional
#           # Log out from the Docker registry at the end of a job
#           logout: # optional, default is true

      # Runs a set of commands using the runners shell
      - name: success
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
