name: Docker Image CI/CD # workflow名称，可以随意改
on: # workflow的事件钩子，告知程序说明时候出发自动部署
  push:
    branches: [ master ] # 在master分支有push操作的时候自动部署
jobs:
  build: # 打包并上传docker镜像
    runs-on: ubuntu-latest # 依赖的环境      
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
      # ${{ secrets.DOCKER_REPOSITORY }}是读取之前在Secret创建的名为DOCKER_REPOSITORY的值
        run: docker build -t registry.cn-shanghai.aliyuncs.com/qbot/cbot:latest ./ # 打包并docker镜像，版本为latest
      - name: Login to Registry # 登录阿里云镜像服务器
        run: docker login --username=${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }} registry.cn-shanghai.aliyuncs.com
      - name: Push Image # 推送镜像，设置版本为latest
        run: docker push registry.cn-shanghai.aliyuncs.com/qbot/cbot:latest
